#!/bin/sh

# Colors
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

cat << "EOF"
     ++++++++++++++  ++++++++++++++            ++++++++++++++         +++++++++++++
  +++++++++++++++++  ++++++++++++++++        ++++++++++++++++      ++++++++++++++++
 ++++++++                      ++++++++    ++++++++               ++++++++         
++++++                            +++++    +++++                 ++++++            
+++++    ++++++++++                +++++  +++++    +++++++++    +++++     +++++++++
++++     ++++++++++                +++++  +++++    +++++++++++  +++++    ++++++++++
+++++    ++++++++++                +++++  +++++    ++++++++++++  ++++     +++++++++
++++++                            +++++    +++++           +++++ ++++++            
 ++++++++                      ++++++++    ++++++++       ++++++  ++++++++         
  +++++++++++++++++  ++++++++++++++++        ++++++++++++++++++    ++++++++++++++++
    +++++++++++++++  ++++++++++++++            ++++++++++++++        ++++++++++++++ 
EOF

echo "${GREEN}Welcome to EdgeOS${NC}"
echo "${BLUE}Secure Edge Computing Platform${NC}"
echo
echo "System Information:"
echo "* $(uname -sr)"
echo
echo "${YELLOW}System:${NC} $(uname -srm)"
if [ -f /etc/edgeos-build-id ]; then
    echo "${YELLOW}Build ID:${NC} $(cat /etc/edgeos-build-id)"
fi
echo "${YELLOW}Hostname:${NC} $(hostname -f 2>/dev/null || hostname)"
echo
